apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: executor-credentials
stringData:
  EXECUTOR_BOOTSTRAP_ADMIN_EMAIL: ENC[AES256_GCM,data:e2P7bb6Eg048VDQgqlm1OSD70r/uS2HF,iv:/rQ7xe0VUypx8QKypeRp9tAZPzas++Y0IBjQgXaO05c=,tag:L6tWZtucdA/IK33C/tP8TQ==,type:str]
  EXECUTOR_BOOTSTRAP_ADMIN_PASSWORD: ENC[AES256_GCM,data:6f5UGfvLtAE8WPzQ0blGmw==,iv:pZJ8wC7lbKJL4sJc4gXu5/+R3rPT5TXG7Jj0TI+SI48=,tag:vjMfKMxohOESD+Oo0LekCQ==,type:str]
  #ENC[AES256_GCM,data:iVTg42pgG+QWwA/Q7W95wyHgj/xspW5EbxFnYrBoQ1s0M9ta1HVWNy1DGLJwSTAfDMNBRmcBco/JAupJyMVg8hbSpThXQ1S0,iv:OVhZ1e4L3HAfdBSHjToa7t1XWr4zzVoPkzvxNfV+5RY=,tag:pmgLyQdyJC3XLO1h6pWxZw==,type:comment]
  #ENC[AES256_GCM,data:T8LSQoXdHqGEN9y5xBxkmKrQLSCo87+9ee5kbr2k4BxV7RbQddjwtuIK7q339BvugLddg3P3qZlDlUiC3ez3xWkV2fr3uWDqMV7oRgftfJ2thw==,iv:SQO4Hv7d9PzuJWRJLn7xHCkvqvY0ZrVayj17M5LTiMU=,tag:BFJHA+Dxii644QOTQTWQuw==,type:comment]
  EXECUTOR_SECRET_KEY: ENC[AES256_GCM,data:5LQE8DnkzPxHTKop2XlBfZTcQaM45hkeWa44upjXLiLO5oB/tQMGSSREEqE=,iv:fwT80InHbJAN3KGnpkXlEDrL2oSdId2zrCKGnGFVw04=,tag:MZg4P0D7HpqPg94QdKT59A==,type:str]
  #ENC[AES256_GCM,data:KBH7k4wzGCLgU4vFGf5Dx7Na3TF8TzGOS81Sghd6Vj1O6glNH1Rj9G5Ut2JpSJd3b/DFkGZm2+O0LDOX+nc0i9xxUx515n9oIU+C8yJhC1Of+AEma1R0s2gNpno=,iv:7TFvGAa2PpGeVt4U6DIEifTLLu6iq/PQ6qqoxp/e5mY=,tag:LmwMkz380WS7NlcG+sNEQw==,type:comment]
  BETTER_AUTH_SECRET: ENC[AES256_GCM,data:kShirDtdYViCmVp+B7NgXvcGV7K54U4nbw6MDHfICaJ6LTkN0zwHVYSlcD4=,iv:KG55r8IbT8LTEA78qrmblbnsOAtBNRuPWHjP37XQ2gk=,tag:4Xy7lQ1HIGoC4t3RR7MBZA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWVhRVWpxeWVNTFRQd3U3
        Z05acStndnNrNEdFZTNmTGlNSjZMWXRJc2lzClQ5bTlMa1IreXZMUVhUVzQ3eWRR
        Vll4K0pXRHh1Y1VONUh4c2NUWm9oakEKLS0tIDAwQ3dCMlZlR3dRV3BLZ2dQVVdU
        QkxndmZ5L0VXWWVHa3lhU3ZCTkNmbWsKfuAPxwGMe1u+8CWTsxGcfSGkLA4AaoZl
        nxvhueV3lIwNcC2JEwCVXpRPOmBgcRrl+pATIRkRE2hvF0JhQAu+LQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1judvvl6kdauw8kwu2ul7g0ffrmg0n9ugvznsh440mp8gzx5fwynsyhxxsc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-25T11:23:52Z"
  mac: ENC[AES256_GCM,data:46SU7i1hVby/n9dW2AJfeu9vs5C3NLzTUc/b/Vn2xCOCSlKLtMtFeZfgRxQblNy6KeRLNE9URsoUmmdZeN20WSFeYFokSyAg/6h5ECdDfhrZ9VX+6zl8wihH2roxh+vT0b52kmBw+uq7hnWu+aCp5aajZIFX6E2NA82aUTCiujI=,iv:G6eAPm3oCfogNZESDkc2DHlpY/LqPK3cRLetwVQURwk=,tag:QldcdS6ycRT5gYi1YVBXPQ==,type:str]
  version: 3.13.3
