apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cloudflare-api-token
    namespace: default
stringData:
    api-token: ENC[AES256_GCM,data:EWNyvPkvtWOIU5ByA2krm6q6hR8zOp63fbbV3hFeuewRTLUhhXoe+7cdNMLdQren4K+7X2g=,iv:5+nHZWZG8ww4lNXn9Bwgm4YBQJCH0am4MmQp7z4hPNM=,tag:XTULHdTBFEZ+tWhLVfC+IA==,type:str]
sops:
    age:
        - recipient: age1judvvl6kdauw8kwu2ul7g0ffrmg0n9ugvznsh440mp8gzx5fwynsyhxxsc
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONnZJUWJRSFRhYjFVODda
              aHdtOFRBMlBXTHdpN3A5aG1JWW0zZW5laHhjCjByc20wb0JQZWVtOGM5N2dFVVFI
              ekR0RGxMMlBJYzdtRk9qZFlTL1lxczQKLS0tIEtXMXBKSG9YOVFCekx6VjVORkc4
              aEVOMk9QNHRpdmVwdHhmZno0MlZObG8KmTt7mXSCH7Jirq1r5oC/Dc2dU3mfDoGM
              jthBfiZumvOUGerB6US+AYZb1CAEEdXercU0/AKgKCP3ebpIlrCleg==
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-19T09:55:28Z"
    mac: ENC[AES256_GCM,data:pnDOThkWMppfvAwfo59q/MevMr6Hl2DwnbawZ1+1LPZQFLqQkIksidlXyBWht7ud7DeD0X1ajBUzxXAyuMWaLx0Ji7kOC+NbZfBDx8nFDlwVChWFhXA5J1gnCwqiZf8rVfqfb7Zep3rycRZciuHZnUm814/L3mTI6lcqN9kg0l8=,iv:kQZ4n6+xAweYcePsu/FV5M11WjAJSFZXm8oFDqA/3lQ=,tag:Xu+bf3AJg4TdDgpsisG6Lg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
