{
 "title": "Storage",
 "description": "Relevant storage metrics from the Proxmox host",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Remaining Media Space",
   "type": "gauge",
   "description": "Remaining free space in `/mnt/media`",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"node-exporter\",nodename=\"proxmox\",mountpoint=\"/mnt/media\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining HDD Space",
   "type": "gauge",
   "description": "Remaining free space in `/mnt/media`",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"node-exporter\",nodename=\"proxmox\",mountpoint=\"/mnt/usb-hdd\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Remaining Root Space",
   "type": "gauge",
   "description": "Remaining free space in `/mnt/media`",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{job=\"node-exporter\",nodename=\"proxmox\",mountpoint=\"/\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}