apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data-pvc
  namespace: uptime-kuma
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
