apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: karakeep
resources:
  - ./ns.yaml
  - ./netpol.yaml
  - ./web-app.yaml
  - ./chrome.yaml
  - ./meilisearch.yaml
  - ./secret.sops.yaml
