apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: karakeep-secrets
# After first signup: create an API key in Karakeep settings and add it as KARAKEEP_API_KEY
stringData:
  #ENC[AES256_GCM,data:PWnjWrj+ihpbmYxOYV++jD74ncvhFiR3+wq1kNvJnTnOLV+LGMuqzWY=,iv:CDnd9RYXWyj11wBK9Rc1WoogRz9orWtwP1JHcXX3dI8=,tag:yvclWk9M1B+yruek7O5RcQ==,type:comment]
  NEXTAUTH_SECRET: ENC[AES256_GCM,data:aS4LcBcHRdVVn6iykynAWFjy+3SKQwKn96pqiOu4zx4GnL4Cg6hIGrb067M=,iv:Y0bPZRlx1DLVA5JtegFvLqzjol0QxyRcHuAcKGyrpF0=,tag:cFaI5fZillIJ62zWSZwZXg==,type:str]
  MEILI_MASTER_KEY: ENC[AES256_GCM,data:aR3juQR2q4vSheT6UMCgIqHzy8iAA+rA9sFgUhumKCjk67pgT02gYBdTRiE=,iv:owOQFeftfudN9D/pvFk6nXiRK3iAUxXUnWhDtertCRk=,tag:MTCZuS/ORb2noulelpzYsA==,type:str]
  #ENC[AES256_GCM,data:Gx9TWgPNO8eqR6Qhc1adqvE7fDFWO5mKqcpmXKw=,iv:3aPLZXj+m3+nXhv9q2rpKUoymgDxDH6lQ7uG9fnFsPk=,tag:jaLH6xwuS/kW1vKXgXPhhQ==,type:comment]
  OPENAI_API_KEY: ENC[AES256_GCM,data:mJ9Nk/Xtdza4UK1IBCLTryHleLB3gdQ6sO13a59dpYI05cF1zuOoMTOFGhsIKpGKW61ts1iKRr/DaB2otj0ra3pE5Hw7lbfsNQ==,iv:7Qog/vOMzk4inV4j1XgZS0jWxAPu1qXRHqJMJSUESdY=,tag:Qa1PC75AzmtovFzPKli3AA==,type:str]
  #ENC[AES256_GCM,data:Hf0K5bHrmCpzkvb5pGK6VyMOXjEgnXPSvXv+mMaS5y6qKVKQaesaeGckiaLjbNxJQp3oezgpSox447271LlLO8vj/PIiXXHU9wlHf2A0U8BC9GWr/gf3,iv:D7gtZ8ojhCQ920LQ8AyZjTQun/fsy9mQtLZrhvdjl+U=,tag:4ryTFhOb4TmOqbAKh03PIw==,type:comment]
  KARAKEEP_API_KEY: ENC[AES256_GCM,data:QIgnAwcz7FXynQt2IXJnBPNHihy+r+AGJgnTfAAQh7xJwWQWX532nZRJawPyAm1Lz9jU5AC6UvUt,iv:jh+AguXKE/1min3lQRqf77vNQHdCiSCneyKRDaBtbjo=,tag:JbG2uOOVP8AvI4wG/VC7mw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJSGorZ05OaTRsVjQ0Z1RM
        c2VCS1pZTG9VMm9HeUtvMUI5R3U3eVZ2T0c4CmpNSDZRTlZSRzFnQnpOaE9Ic3BW
        ZVdNSXFlT2hRbWxOeUtRY1ZQaG9TK28KLS0tIE1yV1luQmVtblp6aXdXUjhkUjU0
        a3RlS3VzNU5kV2xCWUhINzQzNW9hdlEKu+MKfXq3AEdVdvpbAvERB8nH0aMx3NOQ
        QSjtumEEVCOC4Ym7Yk2uzI/COc/Kmf+m7bwmXKc6vmBZ7iLjWHV5mw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1judvvl6kdauw8kwu2ul7g0ffrmg0n9ugvznsh440mp8gzx5fwynsyhxxsc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-28T17:22:03Z"
  mac: ENC[AES256_GCM,data:JZfuFZO1I6tcwUi1z0CQeI+sl0LDbtvhpK7HPwr3SFQH9fFlm1RzrpEuInS00ObsaxC6kCbOqz+LQZR5hSxn4bSI183SPpy6S1lqCdtSwizUz6ZxirB60YcRw2pOHSx8ecCvZ6aiRQeREE00EcGc8bih1cieZPA0WFW+nYD4mtM=,iv:poj5kSpCpw35ocjwKI7Ry8zUonVs8hhCtJWp1KJiJWQ=,tag:1yFoaZ0MQPg4TTRKOD1ZmA==,type:str]
  version: 3.13.3
