apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: qui-session
stringData:
  QUI__SESSION_SECRET: ENC[AES256_GCM,data:XwbpVPASDIdBVHh/won5RNdKKCu1Vx3tRunAvkxwKjkPfs0rHWozX3O0X1irPhInCCus/4B5na6RjuTGIz521Q==,iv:v+gIsWMYIFvILR6ZZ8gm48aVifnlzROsFNoyvvExgTI=,tag:xK/pXUJTNnKr4zOPu72G6g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXTEVFSDE3NzdEU3hLb3Av
        dG13dXlsZWIyOU5wT3RqUmdOd3FrS1EyVlJFClIrSklZajhTTTFhTUFPMjMwQmw5
        VXZKVENqcUU2bnFXVzVpMllyTE1RVkEKLS0tIGdrSXdSUjlVTmJiRHQ3bHBySkpI
        OWZha2JUa1BXcHJVNWdCR2k2ZEI3MEkKkzivom6vEIb3jkkpPnM2qB3A2fhg03Pa
        aWhrc5eZfU8wLqrQ/SojyCCh7uRml3NP5qcf75byRmrAM9g5zMdP3A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1judvvl6kdauw8kwu2ul7g0ffrmg0n9ugvznsh440mp8gzx5fwynsyhxxsc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-25T15:10:42Z"
  mac: ENC[AES256_GCM,data:XX4AHwq3A+fESSfOVZUu8z6lBAXcUlvLGsJXCqpwPcfXoaubg2ALhFlZXh3spQr+ciUb+B6i0/yz61/17F2fQ8AYpX62LZ3xqRNOTdScV3UpeVK7jmegUx+8cM3Y/ISgeDUw8Zp0Qu+CoObfXkbNEGlL8RsZ2DJhD90HZG0bI2E=,iv:xH5fT34M8zSDjCbwz323jRZvX0ltMau9Kft1cALa6wc=,tag:nk/zJrrTkb5MQZHNcERBIQ==,type:str]
  version: 3.13.3
