---
- name: Generate SSH key pairs locally for the management of Proxmox hosts and VMs
  hosts: localhost
  connection: local

  vars_files:
    - ../vars/ssh_users.yaml

  tasks:
    - name: Generate SSH key pairs for users
      ansible.builtin.include_tasks: tasks/generate-key.yaml
      loop: "{{ ssh_users }}"
