---
- name: Configure an Ubuntu cloud image VM with Docker and Portainer
  hosts: ubuntu-vm
  remote_user: murtadha

  tasks:
    - name: Ensure /etc/apt/keyrings exists
      become: true
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker GPG apt key
      become: true
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Get architecture
      changed_when: false
      ansible.builtin.command:
        cmd: dpkg --print-architecture
      register: arch

    - name: Add Docker apt repository
      become: true
      ansible.builtin.deb822_repository:
        name: docker
        types: deb
        uris: https://download.docker.com/linux/ubuntu
        suites: "{{ ansible_facts['lsb']['codename'] }}"
        components: stable
        architectures: "{{ arch.stdout }}"
        signed_by: /etc/apt/keyrings/docker.asc
        state: present
        enabled: true

    - name: Install Docker packages
      become: true
      ansible.builtin.apt:
        update_cache: true
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
          - python3-docker  # Docker SDK for Python, used by community.docker modules
        state: present

    - name: Add the user to the docker group
      become: true
      ansible.builtin.user:
        name: "{{ ansible_facts['user_id'] }}"
        groups:
          - docker
        append: true

    - name: Set logging limits to avoid exhausting disk space
      become: true
      ansible.builtin.copy:
        dest: /etc/docker/daemon.json
        mode: '0644'
        content: |
          {
            "log-driver": "local",
            "log-opts": {
              "max-size": "100m",
              "max-file": "5"
            }
          }
      notify: Restart Docker

    - name: Create Portainer data volume
      become: true
      community.docker.docker_volume:
        name: portainer_data

    - name: Run Portainer CE
      become: true
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:lts
        restart_policy: always
        published_ports:
          - "9443:9443"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer_data:/data

  handlers:
    - name: Restart Docker
      become: true
      loop:
        - docker.service
        - containerd.service
      ansible.builtin.service:
        name: "{{ item }}"
        state: restarted
