apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-admin
  namespace: monitoring
stringData:
  admin-user: ENC[AES256_GCM,data:HXtIs7mvuIU=,iv:HMHVo3k0SBroIj1mOKkNlUh9Db/BmXmqeYj4FT47Mi0=,tag:jDd46DZSlWRltZ80LHUgiA==,type:str]
  admin-password: ENC[AES256_GCM,data:EmRjyARkfKzXjbQg/OrkIw==,iv:Lz34JPKT9ZxWz+Yxfw/VeCpjb8QwIG2tUFVv+plvOWM=,tag:v0oK/vYcCk8LM9K/EusApA==,type:str]
sops:
  age:
    - recipient: age1judvvl6kdauw8kwu2ul7g0ffrmg0n9ugvznsh440mp8gzx5fwynsyhxxsc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUWG1WT09xaDc3LzYxTzU4
        dFN2dW8za2R6TTYzclNLWHBSNzJRNE03ZjBNCnVXSGdkRlR4ck5kQS8rcm81eEtI
        bldDcEI5VWZrSWVyR2pGb000RGRKalEKLS0tIDNSR1dJQ3F4TWVkQVU1UmVPSDBm
        VjU3ajNRQlZmYlRyL1FNL2R3RzZVcjQKMhnbVvDIm355ego8UQCXD0KNINIwbj1h
        M1PFl9p+CHNydkdGvgbp94Mp5VTBIA1j8L2bRi0So1EhN4rsjGEQcg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T07:44:13Z"
  mac: ENC[AES256_GCM,data:THS9skG7cudv7ha8ANVBNAwaxj+hoRZkGpm0xoO7x5xmGwZbAHCdjp2QOCbSN8usY6xLTfLDhP+6BorsSTYbsczSlW4JdbgH4UEHGO0qDIexrmwV0o6+sDX1p9lLBUpp74Bi02unWHEGjzUyNUIwkXzuHl6MG3B9a2qbKe/VwK4=,iv:PaKyeU58zyRa0+Lf6wsOQ8enhdCDO/JR14v/BqHgG3w=,tag:MyoYwPkgBBefi6EWUCkS9A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
