---
- name: Create a Proxmox template-ready machine
  hosts: proxmox_fresh_vms

  tasks:
    - name: Update apt cache and upgrade
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: full

    - name: Install cloud-init
      become: true
      ansible.builtin.apt:
        name: cloud-init
        state: present

    - name: Install qemu-guest-agent
      become: true
      ansible.builtin.apt:
        name: qemu-guest-agent
        state: present

    - name: Start qemu-guest-agent
      become: true
      ansible.builtin.systemd:
        name: qemu-guest-agent
        state: started

    - name: Restart the system to apply changes
      become: true
      ansible.builtin.reboot:
        reboot_msg: "Rebooting the system to apply changes"

    - name: Remove SSH host files
      become: true
      ansible.builtin.file:
        state: absent
        path: /etc/ssh/ssh_host_*

    - name: Empty the /etc/machine-id file
      become: true
      ansible.builtin.copy:
        src: /etc/machine-id
        dest: /etc/machine-id
        content: ""
        mode: # read read read , root: root

    - name: Ensure /var/lib/dbus/machine-id links to /etc/machine-id
      become: true
      ansible.builtin.file:
        src: /var/lib/dbus/machine-id
        dest: /etc/machine-id
        state: link

    - name: Clean apt cache
      become: true
      ansible.builtin.apt:
        autoclean: true # sudo apt clean
        autoremove: true # sudo apt autoremove

    - name: Clean cloud-init
      become: true
      ansible.builtin.command: cloud-init clean
      changed_when: true

    - name: Power off the machine
      become: true
      ansible.builtin.command: poweroff
      changed_when: true
