apiVersion: v1
kind: Service
metadata:
  name: e-store-backend
  labels:
    app: e-store-backend
spec:
  type: ClusterIP
  selector:
    app: e-store-backend
  ports:
    - name: http
      port: 4210
      protocol: TCP
      targetPort: http
