apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: e-store-db
stringData:
  MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:e2xnk1ItuJ31EWhNYak9tUrO+vW8avCOR52EWUrkuLXjsD4/U5FTtjKdsqnBZD7B,iv:p9yAKYURJHmrbFX5zqlp9kXl0zRCbT1689N1v8JqAEs=,tag:uHPUx9oMqmtzKoP0bndpKQ==,type:str]
  MYSQL_DATABASE: ENC[AES256_GCM,data:W+ZS1j6y,iv:sM7RNH/XHMuPOrXocmz3xFe6J1JGmztjo5UtAfE2Aio=,tag:DGk3e+IeJQhIHP5XwqjA9w==,type:str]
  MYSQL_USER: ENC[AES256_GCM,data:+eRphmuu,iv:BtspmO4IJ/Uvq/NzURgYwKoGHThh1gHjuqR+kYffRUI=,tag:irthzKN735kREaNLTqmEFw==,type:str]
  MYSQL_PASSWORD: ENC[AES256_GCM,data:Dddndp7IvZIKB+P6dgvmOFH6gARWPk6BSyfUxsL9nQ8XBFuiZc2sD4L1AyMN8DrL,iv:GHF7xgUwek4kzafEGXtUyDLhRBqYhKj6DjyPM5a2Z0U=,tag:a1tLZ8qZQOZQC8vVwi1tPQ==,type:str]
  DSN: ENC[AES256_GCM,data:XQbkptc+SUQZGguGS/csffQSVRfkkDv6I5FC9V+drOecvg1s0XjZO/7v3IF28NxsDbBkKjdDGYXHmQXMSQjxnIzZCUGSfyPM/gh13TyZmVD+z3sWAL0dpHRcwxXo9qTtokhy61akkKjIpu031tdINuJjyfooZd7H/dP++2x3qsDdoh7Mjt7z6bYid30=,iv:41obwgkzPtIV/HWYrDcUp3w9DWHhFr1p5mZ1F6EwQpk=,tag:hn3K2G0I+YIo6uM0joV82Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5R2lpSGUyOWpOdkcxWWxj
        WWVSczFzdStWcmVpWUdkZE41QzROQ2xQa1VRCk16SkV1SFRpRUNEWU1KSmIwS3lZ
        WUNkSjc1Q3NBOVRKRmpTMHMyWTZRMmsKLS0tIGo0UlRjdlBFenUzRGtCdlZWbFpl
        Ymt0c1QvSXhQZ3VaUlc3bFgzeU9Nbm8KNRctOFx4Bds4cWXPuG9syeMucG6ZulDh
        kOO5heBhLHZSLWRcy1kbBtOs5EPY26qqFYhbLtjhkNJdn0Yb6oAWEA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1judvvl6kdauw8kwu2ul7g0ffrmg0n9ugvznsh440mp8gzx5fwynsyhxxsc
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T16:01:45Z"
  mac: ENC[AES256_GCM,data:7+XlxP25NB99bUe6BogZx6ThDkTw63WYzMxLatQ73am+m8TfcZWSgYKDw1HxfqDNYxNa7/RoO1xo3xqSQgAVJo0vyhuyeUxLgE5ZMt31A4p1AWFpiWfagGLn83X/UCAFFjy282d25QFC2PHGhEh0a9g9+2LJUES4eWx0lde8H2Q=,iv:HHMsIwpbSzCsdwdfb7LRe5QTzwhtfBZVlatXh+gx5lU=,tag:PoLTO41SSeShh+2376wKYw==,type:str]
  version: 3.13.1
