---
- name: Generate SSH key pairs for remote Proxmox management
  hosts: localhost
  connection: local

  vars:
    # base directory for keys is ~/.ssh/keys
    ssh_users: [
      { type: "automation user", key_filename: test1 },
      { type: "regular user", key_filename: test2 }
    ]

  tasks:
    - name: Generate SSH key pairs for users
      ansible.builtin.include_tasks: tasks/generate-key.yaml
      loop: "{{ ssh_users }}"
