---
- name: Prepare Proxmox nodes for remote management
  hosts: proxmox-hosts
  remote_user: root
  vars:
    # automation_user: "{{ ssh_users | selectattr('type', 'eq', 'automation user') | map(attribute='user_name') | first }}"
    # automation_user_pub_key: "{{ ssh_users | selectattr('type', 'eq', 'automation user') | map(attribute='pub_key') | first }}"
    # regular_user: "{{ ssh_users | selectattr('type', 'eq', 'regular user') | map(attribute='user_name') | first }}"
    # regular_user_pub_key: "{{ ssh_users | selectattr('type', 'eq', 'regular user') | map(attribute='pub_key') | first }}"
    automation_user: "{{ ssh_users[0]['user_name'] }}"
    automation_user_pub_key: "{{ ssh_users[0]['pub_key'] }}"
    regular_user: "{{ ssh_users[1]['user_name'] }}"
    regular_user_pub_key: "{{ ssh_users[1]['pub_key'] }}"
  vars_files:
    - ../vars/secrets.yaml
    - ../vars/ssh_users.yaml

  tasks:
    - name: Supply the public SSH key generated to the root user first
      ansible.posix.authorized_key:
        key: "{{ lookup('file', regular_user_pub_key) }}"
        user: root
        exclusive: true
        state: present

    - name: Install the sudo package
      ansible.builtin.package:
        name: sudo
        state: present

    - name: Create a specific automation user for performing future Ansible tasks
      block:
        - name: Create the automation user
          ansible.builtin.user:
            name: "{{ automation_user }}"
            state: present
            groups:
              - sudo
            shell: /bin/bash
            comment: Automation User
            # password: '!' # pass is enabled for the TF provider (preferred over API tokens)
            password: "{{ automation_user_pass | password_hash('sha512', salt, rounds=657235) }}"

        - name: Supply the public SSH key generated for the automation user
          ansible.posix.authorized_key:
            key: "{{ lookup('file', automation_user_pub_key) }}"
            user: "{{ automation_user }}"
            exclusive: true
            state: present

        - name: Allow sudo without password for the automation user
          ansible.builtin.lineinfile:
            path: "/etc/sudoers"
            search_string: "{{ automation_user }}"
            line: "{{ automation_user }} ALL=(ALL) NOPASSWD: ALL"
            state: present
            validate: "/usr/sbin/visudo -cf %s"

    - name: Create a regular user for other manual management tasks
      block:
        - name: Create the regular user
          ansible.builtin.user:
            name: "{{ regular_user }}"
            state: present
            groups:
              - sudo
            shell: /bin/bash
            password: "{{ regular_user_pass | password_hash('sha512', salt, rounds=657235) }}"

        - name: Supply the public SSH key generated for the regular user
          ansible.posix.authorized_key:
            key: "{{ lookup('file', regular_user_pub_key) }}"
            user: "{{ regular_user }}"
            exclusive: true
            state: present

    - name: Disable SSH password authentication on the server
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        search_string: "PasswordAuthentication"
        line: "PasswordAuthentication no"
        state: present
        validate: "/usr/sbin/sshd -t -f %s"
      notify: Restart SSH

    - name: Make the required (equivalent) changes on the PVE Web Gui side
      block:
        - name: Check if the admins group exists
          changed_when: false
          ansible.builtin.command:
            cmd: pveum group list
          register: pve_groups

        - name: Create the admins group
          when: not pve_groups.stdout is search('admins')
          changed_when: not pve_groups.stdout is search('admins')
          ansible.builtin.command:
            cmd: 'pveum group add admins --comment "Admins Group"'

        - name: Check if the admins group has 'Administrator' permissions
          changed_when: false
          ansible.builtin.command:
            cmd: pveum acl list
          register: pve_perms

        - name: Assign the Administrator role (i.e. permissions) to the 'admins' group
          when: not pve_perms.stdout is search('admins')
          changed_when: not pve_perms.stdout is search('admins')
          ansible.builtin.command:
            cmd: 'pveum acl modify / --roles Administrator --groups admins'

        - name: Check for the existent Web GUI users
          changed_when: false
          ansible.builtin.command:
            cmd: pveum user list
          register: pve_web_users

          # The password used for Web GUI is going to be the same one setup for the underlying PAM user
        - name: Mirror (i.e. create) the regular user if not present
          when: not pve_web_users.stdout is search(regular_user + '@pam')
          changed_when: not pve_web_users.stdout is search(regular_user + '@pam')
          ansible.builtin.command:
            # TODO: use a jinja filter to capitalise the first letter of the first name using the user name
            cmd: "pveum user add {{ regular_user }}@pam --email {{ email }} --firstname 'Murtadha' --groups admins"
          # NOTE: TFA needs to be enabled from the web GUI (for both this and the root user)

          # The password used for Web GUI is going to be the same one setup for the underlying PAM user
        - name: Mirror (i.e. create) the automation user if not present
          when: not pve_web_users.stdout is search(automation_user + '@pam')
          changed_when: not pve_web_users.stdout is search(automation_user + '@pam')
          ansible.builtin.command:
            # use a jinja filter to capitalise the first letter of the first name using the user name
            cmd: "pveum user add {{ automation_user }}@pam --groups admins"

  handlers:
    - name: Restart SSH
      ansible.builtin.service:
        name: sshd
        state: restarted
