apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: grafana-admin
  namespace: monitoring
stringData:
  admin-user: ENC[AES256_GCM,data:7l+o4LQuFLw=,iv:HMHVo3k0SBroIj1mOKkNlUh9Db/BmXmqeYj4FT47Mi0=,tag:fjLqs/wMzLoFX9nd8L0ZjA==,type:str]
  admin-password: ENC[AES256_GCM,data:0e6oEOoV33jJNNH6Nkxm5A==,iv:Lz34JPKT9ZxWz+Yxfw/VeCpjb8QwIG2tUFVv+plvOWM=,tag:XgWLnyLLb0umen8gxrGEGg==,type:str]
sops:
  age:
    - recipient: age1judvvl6kdauw8kwu2ul7g0ffrmg0n9ugvznsh440mp8gzx5fwynsyhxxsc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhT0lOUHgrUTJjRUdaU1Rq
        YzJFZVdKb2cwQVdBcWMrM2dPMzFCdTVBRW1zCkZkQ1RIRHN6dWlsSzNNVGpQdjR1
        UmpvbDI4MTFCWHJOQm44VXVsaUdtWDAKLS0tIDBMWDc3L3BKVHluOVVSeXZyS1Mr
        VUtYZ3NkeVZjVHhPdEVGOEkrVE9Ud1UKA5tS/WS5lUA4Ao1CxMoMUBef/UYYdT2r
        1z1eCsJgMGF97f9gHkS857jz1rGQT91HQLgL2SXh+l7ueN8kYsx1NA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T09:32:49Z"
  mac: ENC[AES256_GCM,data:i/VrLrnByaufKlro25FWtS+GV4DCUc/k6TIp4ZH3cYDZMtB4XaheZKH0WCLEHyktOapdoirzUD1Awn0Mfr9/ynYMTTTyIpeKCWqwyxElFNZPSDCssy83vUp94aZgofqo/9VdPsJSCY9mKGFaG84wcRaFkM+Z+AJhB9Eh8+GvLYM=,iv:uJ6+lGcN2bfoRqSQf1wmWM4GDzdOwFTKMuquwmNjdl4=,tag:VpsDoDvbd2opfpfZTk8TpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
