---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 12h
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: "1.11.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
  values:
    defaultSettings:
      defaultDataPath: /var/mnt/longhorn
      defaultReplicaCount: 2 # Default number of replicas for volumes created using the Longhorn UI
    persistence:
      defaultClassReplicaCount: 2 # Replica count of the default Longhorn StorageClass
      # reclaimPolicy: Retain
    # metrics:
    #   serviceMonitor:
    #     enabled: true # create a Prometheus ServiceMonitor resource for Longhorn Manager components
    #     # -- Additional labels for the Prometheus ServiceMonitor resource.
    #     additionalLabels: {}
    #     # ...see other options
    # httproute:
    #   enabled: true # generate HTTPRoute records for the Longhorn UI service using Gateway API
    #   # ...see other options
