apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: cloudflare-api-token
  namespace: default
stringData:
  api-token: ENC[AES256_GCM,data:+Wsr7h5PSagK6X4wlaEh+4h8tT0bmls1/XaQgoBOclwGwZlrBV5Tkwpkt+21YgcM8H/FA3s=,iv:FqQTZtjaSi8oTOVa/XOfA32Wqpi3P0xg5IGuWBdDpnE=,tag:S3WT/qix8XVBBDQKKjcOMA==,type:str]
sops:
  age:
    - recipient: age1judvvl6kdauw8kwu2ul7g0ffrmg0n9ugvznsh440mp8gzx5fwynsyhxxsc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiT1ZTUDFlajdhYTdaQnk1
        NzJ5azAwemRLeFVwOUl4ODlVL3lXN0hNYXo0CmpjOERiV1BpL1Fmd2x2aTk1L2RG
        dGE1cVcxRFc4QWFzY1pJNEMrNDkyYVEKLS0tIEk1SEppKzF4ajlQNmJtS1oxcHJk
        T280NkV4TE83T2owR1pDd2Y4cmx4NzQK2QLXdRxPWYE2v4ifIEITlsqp7QD5QxG8
        oenlTWj053wWFETHZNNz4WjNuAWqz6tJrAfr2gwKowjzxfXhNd9sHQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-19T09:09:35Z"
  mac: ENC[AES256_GCM,data:cMGh+7+mLVxhOKtpU/0+g4RI+wvNAYY+InZM/mgIhTdDArqG3PEtswuCHjyvzpKryzKPEp3O0QhTcaviwf6vF9En6ZVJa5re5gxvoQv8jjO9+82vtxwU0GZw61yJa59hQSWLYuKDhiSCXZR5FXQ4Q8C7/TO1No5DCoqmrSaFg3Y=,iv:zk/Phyy8xBO5EfegHqjCvpM4EIPEh/syMtQbX2xhJj8=,tag:tHWzWK4A9+bcrtlLU2macg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
